# Generated by Django 5.0.4 on 2024-05-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField()),
                ('date_due', models.DateTimeField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('house_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.payments')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.landlord')),
                ('tenant', models.ForeignKey(db_column='house_number', on_delete=django.db.models.deletion.CASCADE, to='rent.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='tenant',
            field=models.ForeignKey(db_column='house_number', on_delete=django.db.models.deletion.CASCADE, to='rent.tenant'),
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_name', models.CharField(max_length=10)),
                ('utility_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.landlord')),
            ],
        ),
    ]
