# Generated by Django 5.0.4 on 2024-07-03 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField()),
                ('date_due', models.DateTimeField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100, unique=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rent.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('house_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('date_moved_in', models.DateTimeField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.landlord')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='rent.property')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.payments')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.landlord')),
                ('tenant', models.ForeignKey(db_column='house_number', on_delete=django.db.models.deletion.CASCADE, to='rent.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='tenant',
            field=models.ForeignKey(db_column='house_number', on_delete=django.db.models.deletion.CASCADE, to='rent.tenant'),
        ),
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom_count', models.CharField(max_length=128)),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_details', to='rent.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_name', models.CharField(max_length=10)),
                ('utility_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_houses', models.IntegerField()),
                ('number_of_1_bedroom_houses', models.IntegerField(default=0)),
                ('number_of_2_bedroom_houses', models.IntegerField(default=0)),
                ('number_of_3_bedroom_houses', models.IntegerField(default=0)),
                ('number_of_4_bedroom_houses', models.IntegerField(default=0)),
                ('base_rent_1_bedroom', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_rent_2_bedroom', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_rent_3_bedroom', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_rent_4_bedroom', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='rent.property')),
                ('utilities', models.ManyToManyField(related_name='properties', to='rent.utilities')),
            ],
        ),
    ]
